### ISSUE TITLE
Checklist sidebar

### ISSUE THREAD

**Issue by jenstornell** [getsquares/plugin-markdown#63]
## Warnings

- [x] One h1 tag
- [x] Alt tags on all images

## Recommendations

- [x] At least two h2 tags
- [x] h3-h6 found
- [x] Word count
- [x] h1 char length
- [x] At least 2 images
- [x] At least 2 outlinks
- [x] Not too long paragraphs

## Stats

- [x] Count h1-h6
- [x] Count lists
- [x] Count images
- [x] Count paragraphs
- [x] Count sentences
- [x] Reading time

**Comment by jenstornell** [comment]
✔️
